import * as bodyParser from 'body-parser';
import * as express from 'express';
import { RegisterRoutes } from '../routes';
import * as cors from 'cors';
import * as path from 'path';

export default function startExpress(app: express.Express): void {
  app.use(bodyParser.json());
  app.use(cors());
  app.use(express.static(path.join(__dirname, '../public')));

  //register all routes from the routes generated by tsoa
  RegisterRoutes(app);
  
}




