import bodyParser from 'body-parser';
import express, { Express } from 'express';
import logger from 'morgan';
import { RegisterRoutes } from '../routes';
import cors from 'cors';
import path from 'path';

export default function startExpress(app: Express) {
  app.use(logger('dev'));
  app.use(bodyParser.json());
  app.use(cors());
  app.use(express.static(path.join(__dirname, '../public')));

  //register all routes from the routes generated by tsoa
  RegisterRoutes(app);

}




