import * as express from 'express';
import { RegisterRoutes } from '../routes';
import cors from 'cors';
import * as path from 'path';
import useSwagger from './swagger';

export default function(app: express.Express): void {
    app.use(express.json());
    app.use(cors());
    app.use(express.static(path.join(__dirname, '../public')));

    //register all routes from the routes generated by tsoa
    RegisterRoutes(app);

    console.log('✌️ Express Loaded.');

    useSwagger(app);
    console.log('🙉 Swagger Loaded.');

};